name: 'Linux'

env:
  LIBRARIES_BRANCH: libraries-OS-COMPILER
  NCINE_SOURCE_BRANCH: BRANCH_NAME
  DEPLOY_MESSAGE:
    "Push artifact from GitHub Actions build ${{ github.run_number }} with id ${{ github.run_id }}

     - PROJECT_NAME artifact from branch 'BRANCH_NAME' with commit id ${{ github.sha }}"
  DEPLOY_BRANCH: PROJECT_NAME-BRANCH_NAME-OS-COMPILER

on: [push, workflow_dispatch]

jobs:
  Linux:
    strategy:
      fail-fast: false
      matrix:
        include:
        - BuildType: Debug
          CC: gcc
          CXX: g++

        - BuildType: Release
          CC: gcc
          CXX: g++

        - BuildType: BinDist
          CC: gcc
          CXX: g++

        - BuildType: Debug
          CC: clang
          CXX: clang++

        - BuildType: Release
          CC: clang
          CXX: clang++

        - BuildType: BinDist
          CC: clang
          CXX: clang++

    runs-on: 'ubuntu-20.04'

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v2

    - name: 'Install nCine Build Dependencies'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev

    - name: 'Unshallow Git Repository for Versioning'
      if: matrix.BuildType == 'BinDist'
      run: |
        git fetch --unshallow || true

    - name: 'Download nCine-libraries and project data'
      run: |
        export OS=linux
        export CC=${{ matrix.CC }}

        export LIBRARIES_BRANCH=`echo $LIBRARIES_BRANCH | sed 's/OS/'"$OS"'/'`
        export LIBRARIES_BRANCH=`echo $LIBRARIES_BRANCH | sed 's/COMPILER/'"$CC"'/'`

        cd ..
        git clone https://github.com/nCine/nCine-libraries-artifacts.git
        cd nCine-libraries-artifacts
        git checkout $LIBRARIES_BRANCH
        LIBRARIES_FILE=$(ls -t | head -n 1) && tar xpzf $LIBRARIES_FILE
        mv nCine-external ..
        cd ..
        rm -rf nCine-libraries-artifacts

        git clone https://github.com/$GITHUB_REPOSITORY-data.git

    - name: 'Download nCine source and data'
      run: |
        export BRANCH_NAME=$(git describe --tags --exact-match 2> /dev/null || git symbolic-ref -q --short HEAD || git rev-parse --short HEAD)
        export NCINE_SOURCE_BRANCH=`echo $NCINE_SOURCE_BRANCH | sed 's/BRANCH_NAME/'"$BRANCH_NAME"'/'`

        cd ..
        git clone https://github.com/nCine/nCine-data.git
        git clone https://github.com/nCine/nCine.git --branch $NCINE_SOURCE_BRANCH

    - name: 'CMake Configuration and Make of nCine as a static library'
      run: |
        cd ../nCine
        if [[ "${{ matrix.BuildType }}" == "BinDist" ]]; then
          export NCINE_BUILD_TYPE=Release
        else
          export NCINE_BUILD_TYPE=${{ matrix.BuildType }}
        fi
        export CMAKE_ARGS="-B ../nCine-build-$NCINE_BUILD_TYPE -D CMAKE_BUILD_TYPE=$NCINE_BUILD_TYPE -D NCINE_DYNAMIC_LIBRARY=OFF -D IMGUI_VERSION_TAG=docking -D NCINE_PREFERRED_BACKEND=SDL2 -D NCINE_WITH_THREADS=OFF -D NCINE_WITH_WEBP=OFF -D NCINE_WITH_AUDIO=OFF -D NCINE_WITH_SCRIPTING_API=OFF -D NCINE_BUILD_TESTS=OFF"

        export CC= ${{ matrix.CC }}
        export CXX=${{ matrix.CXX }}
        export CMAKE_ARGS="$CMAKE_ARGS -D CMAKE_PREFIX_PATH=$(pwd)/../nCine-external"

        cmake $CMAKE_ARGS
        cd ..
        make -j2 -C nCine-build-$NCINE_BUILD_TYPE

    - name: 'CMake Configuration'
      run: |
        export PROJECT_NAME=${GITHUB_REPOSITORY##*/}

        export CMAKE_ARGS="-B ../$PROJECT_NAME-build-${{ matrix.BuildType }}"

        export CC= ${{ matrix.CC }}
        export CXX=${{ matrix.CXX }}
        export CMAKE_ARGS="$CMAKE_ARGS -D CMAKE_PREFIX_PATH=$(pwd)/../nCine-external"

        if [[ "${{ matrix.BuildType }}" == "BinDist" ]]; then
          cmake $CMAKE_ARGS -D NCPROJECT_OPTIONS_PRESETS=${{ matrix.BuildType }} -D CMAKE_INSTALL_PREFIX="" -D nCine_DIR=$(pwd)/../nCine-build-Release
        else
          cmake $CMAKE_ARGS -D CMAKE_BUILD_TYPE=${{ matrix.BuildType }} -D nCine_DIR=$(pwd)/../nCine-build-${{ matrix.BuildType }}
        fi

    - name: 'Make'
      run: |
        export PROJECT_NAME=${GITHUB_REPOSITORY##*/}

        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/../nCine-external/lib
        make -j2 -C ../$PROJECT_NAME-build-${{ matrix.BuildType }}

    - name: 'Package'
      if: matrix.BuildType == 'BinDist'
      run: |
        export PROJECT_NAME=${GITHUB_REPOSITORY##*/}
        make package -C ../$PROJECT_NAME-build-${{ matrix.BuildType }}

    - name: 'Generate and Push Documentation'
      if: matrix.BuildType == 'BinDist' && matrix.CC == 'gcc'
      env:
        PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        cd ../SpookyGhost-data/docs
        export GEM_HOME=~/.gem
        export GEM_PATH=~/.gem
        gem install asciidoctor
        export PATH=$GEM_HOME/bin:$PATH
        asciidoctor documentation.adoc

        cd ../..
        git clone https://$PUBLIC_REPO_TOKEN@github.com/SpookyGhost2D/docs.git >/dev/null 2>&1
        cd docs
        git rm -r . >/dev/null 2>&1
        cp -p ../SpookyGhost-data/docs/* .
        rm documentation.adoc
        mv documentation.html index.html
        git add .

        git commit --amend -m "Initial commit" || git commit -m "Initial commit"
        git push --force || git push --set-upstream origin master

    - name: 'Push Artifacts'
      if: matrix.BuildType == 'BinDist'
      env:
        PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        export PROJECT_NAME=${GITHUB_REPOSITORY##*/}
        export BRANCH_NAME=$(git describe --tags --exact-match 2> /dev/null || git symbolic-ref -q --short HEAD || git rev-parse --short HEAD)
        export DEPLOY_MESSAGE=`sed 's/PROJECT_NAME/'"$PROJECT_NAME"'/' <<< "$DEPLOY_MESSAGE"`
        export DEPLOY_MESSAGE=`sed 's/BRANCH_NAME/'"$BRANCH_NAME"'/' <<< "$DEPLOY_MESSAGE"`

        export OS=linux
        export CC=${{ matrix.CC }}
        export PROJECT_EXT=tar.gz

        cd ..
        export DEPLOY_BRANCH=`echo $DEPLOY_BRANCH | sed 's/PROJECT_NAME/'"$PROJECT_NAME"'/'`
        export DEPLOY_BRANCH=`echo $DEPLOY_BRANCH | sed 's/BRANCH_NAME/'"$BRANCH_NAME"'/'`
        export DEPLOY_BRANCH=`echo $DEPLOY_BRANCH | sed 's/OS/'"$OS"'/'`
        export DEPLOY_BRANCH=`echo $DEPLOY_BRANCH | sed 's/COMPILER/'"$CC"'/'`
        git clone https://$PUBLIC_REPO_TOKEN@github.com/$GITHUB_REPOSITORY-artifacts.git >/dev/null 2>&1
        cd $PROJECT_NAME-artifacts

        git checkout $DEPLOY_BRANCH || git checkout --orphan $DEPLOY_BRANCH
        git reset
        git clean -f
        git rm * || true
        mv -f ../$PROJECT_NAME-build-${{ matrix.BuildType }}/*.$PROJECT_EXT .
        git add *.$PROJECT_EXT
        git commit --amend -m "$DEPLOY_MESSAGE" || git commit -m "$DEPLOY_MESSAGE"
        git push --force || git push --set-upstream origin $DEPLOY_BRANCH
